name: hapis
base: core18
version: '1.0.10'
summary: Hapi Server Linux-x64
description: |
  Hapi Server Linux-x64
grade: devel
confinement: devmode

apps:
  hapis:
    command: /snap/hapis/current/bin/node /snap/hapis/current/test/server-test.js 
  bash:
    command: /bin/bash

parts:
  hapis:
    #source: https://github.com/hapi-server/server-nodejs/releases/download/v1.0.9/hapi-server-v1.0.9-linux-x64.tgz
    source-type: local
    source: .
    plugin: dump
  gnu-bash:
    source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
    plugin: nil


#--logdir="/home/parallels/hapi_logs" --metadata_dir="/home/parallels/hapi_metadata" 
#cd /snap/hapi-server/current && /bin/node test/server-test.js